<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE issuezilla [
    <!-- This DTD describes a structure that contains one or more         -->
    <!-- IssueZilla issues. IssueZilla is a derivative of BugZilla        -->
    <!-- (http://bugzilla.mozilla.org) developed for use with SourceCast  --> 
    <!-- $Id: issuezilla.dtd 34364 2003-11-18 00:30:16Z kmaples $  -->
    
    <!ELEMENT issuezilla (issue+)>
    
      <!--  Attributes of the root element 'issuezilla':                  -->   
      <!--                                                                -->
      <!--  version     : Current version of IssueZilla.                  -->
      <!--  urlbase     : Full url to source installation of issueZilla.  -->
      <!--  maintainer  : Email address of person responsible for         -->
      <!--                installation usually 'webmaster@foo.com'        -->
      <!--  exporter    : Email address of the individual performing the  -->
      <!--                XML export.                                     -->
      <!--  charset     : The originating charset for this issue.         -->
      <!--  dtd_version : Version of this DTD; the cvs revision number.   -->
      
      <!ATTLIST issuezilla version CDATA #REQUIRED>
      <!ATTLIST issuezilla urlbase CDATA #REQUIRED>
      <!ATTLIST issuezilla maintainer CDATA #REQUIRED>
      <!ATTLIST issuezilla exporter CDATA #IMPLIED>
      <!ATTLIST issuezilla charset CDATA #REQUIRED>
    
      <!-- Attributes of the Helm project from whence this export came:   -->  
    
      <!ATTLIST issuezilla project_domain CDATA #IMPLIED>
      <!ATTLIST issuezilla project_name CDATA #IMPLIED>
      <!ATTLIST issuezilla project_id CDATA #IMPLIED>
      
      <!-- Current cvs revision: $Revision: 1.6 $                         -->
      <!-- Revision above should match hardcoded value below (hard-coded  -->
      <!-- to facilitate development):                                    -->
      <!ATTLIST issuezilla dtd_version CDATA #FIXED "Revision: 1.2">
    
      <!--  Elements comprising an issue.                                 -->
    
      <!ELEMENT issue ( issue_id, (issue_status, priority, resolution,
          component, version, rep_platform, assigned_to, 
          delta_ts, subcomponent, reporter, target_milestone?, issue_type, 
          creation_ts, qa_contact?, status_whiteboard?, issue_file_loc?,
          votes?, op_sys, short_desc, keywords*, dependson*, blocks*, 
          is_duplicate?, has_duplicates*, cc*, long_desc+, attachment*, 
          activity* 
        )? 
      ) >
    
        <!-- Attribute(s) of the 'issue' element:                             -->
        <!--                                                                  -->
        <!-- status_code  : Error code if issue requested is missing, or user -->
        <!--                performing the operation does not have the        -->
        <!--                necessary role.  Uses HTTP codes as defined in    -->
        <!--                RFC 2616; will always return a three-digit code.  -->
        <!-- status_message : String corresponding to status_code above.      -->
    
        <!ATTLIST issue status_code    (200|401|404) #REQUIRED>
        <!ATTLIST issue status_message (OK|Unauthorized|NotFound) #REQUIRED>
    
        <!-- Elements of issue and their definitions:                          -->
        <!--                                                                   -->
        <!-- issue_id     : ID of this issue (unique key).                     -->
        <!-- issue_status : Current status of this issue.                      -->
        <!-- priority     : Priority (severity) assigned to issue.             -->
        <!-- resolution   : The issue's resolution, if any                     -->
        <!-- component    : Product against which issue is reported.           -->
        <!-- version      : Version associated with component.                 -->
        <!-- platform     : Platform issue reported against (e.g. linux, etc.).-->
        <!-- assigned_to  : Email of person issue currently assigned to.       -->
        <!-- delta_ts     : Last modified timestamp ('yyyy-mm-dd hh:mm:ss').   -->
        <!--                                                                   -->
        <!-- subcomponent     : Component of component issue reported against. -->
        <!-- reporter         : Email of initial issue reporter.               -->
        <!-- target_milestone : Milestone for this issue's resolution.         -->
        <!-- issue_type       : Nature of issue, e.g. defect, task, etc.       -->
        <!-- creation_ts      : Issue creation timestamp ('yyyy-mm-dd hh:mm:ss').-->
        <!-- qa_contact       : Email of the QA contact for this issue.        --> 
        <!-- status_whiteboard: Free text 'whiteboard' for issue comments.     -->
        <!-- issue_file_loc   : URL related to issue                           -->
        <!-- votes            : current votes for issu                         -->
        <!-- op_sys           : Operating system issue reported against.       -->
        <!-- short_desc       : Short description of issue.                    -->
    
        <!ELEMENT issue_id (#PCDATA)>
        <!ELEMENT issue_status (#PCDATA)>
        <!ELEMENT priority (#PCDATA)>
        <!ELEMENT resolution (#PCDATA)>
        <!ELEMENT component (#PCDATA)>
        <!ELEMENT version (#PCDATA)>  
        <!ELEMENT rep_platform (#PCDATA)> 
        <!ELEMENT assigned_to (#PCDATA)>
        <!ELEMENT delta_ts (#PCDATA)>     
        <!ELEMENT subcomponent (#PCDATA)>
        <!ELEMENT reporter (#PCDATA)>  
        <!ELEMENT target_milestone (#PCDATA)>
        <!ELEMENT issue_type (#PCDATA)>
        <!ELEMENT creation_ts (#PCDATA)>   
        <!ELEMENT qa_contact (#PCDATA)>
        <!ELEMENT status_whiteboard (#PCDATA)>
        <!ELEMENT issue_file_loc (#PCDATA)>
        <!ELEMENT votes (#PCDATA)>
        <!ELEMENT op_sys (#PCDATA)> 
        <!ELEMENT short_desc (#PCDATA)>
    
        <!-- Data from the longdescs table for this issue id.  Essentially   -->
        <!-- the log of additional comments.                                 -->
        <!--                                                                 --> 
        <!-- who        : Email of person posting long_desc.                 --> 
        <!-- issue_when : Timestamp when long_desc added ('yyy-mm-dd hh:mm') -->
        <!-- thetext    : Free text that comprises the long desc.            -->
    
        <!ELEMENT long_desc (who, issue_when, thetext)>
    
          <!ELEMENT who (#PCDATA)>
          <!ELEMENT issue_when (#PCDATA)>
          <!ELEMENT thetext (#PCDATA)>
    
        <!-- 'optional' elements.                                           
             keywords       : List of keywords for this issue.                   
             dependson      : List of local issue IDs that depend on this one.   
             blocks         : List of local issue IDs blocked by this one.       
             is_duplicate   : The issue which this issue was closed as a 
                              duplicate of.
             has_duplicates : Other issues which were closed as a duplicate 
                              of this issue.
             cc             : List of email addresses of interested parties.     
    
             NOTE: elements of 'blocks', 'dependson', 'is_duplicate' and 
             'has_duplicates' are defined elsewhere in this document.        -->
    
        <!ELEMENT keywords (#PCDATA)>
        <!ELEMENT dependson (issue_id, who, when)>
        <!ELEMENT blocks (issue_id, who, when)>
        <!ELEMENT is_duplicate (issue_id, who, when)>
        <!ELEMENT has_duplicates (issue_id, who, when)>
        <!ELEMENT cc (#PCDATA)>
    
        <!-- Data pertaining to attachments.  NOTE - some of these fields    -->
        <!-- are currently unimplemented (ispatch, filename, etc.).          -->
    
        <!ELEMENT attachment (mimetype, attachid, date, desc, ispatch*, filename, 
            submitter_id, submitting_username, data, attachment_iz_url)>
    
          <!-- encoding   : How the inline attachment is encoded.            -->
    
          <!ATTLIST attachment encoding CDATA #FIXED "Base64" >
    
          <!-- mimetype     : Mime type for the attachment.                  -->
          <!-- attachid     : A unique id for this attachment.               -->
          <!-- date         : Timestamp of when added 'yyyy-mm-dd hh:mm'     -->
          <!-- desc         : Short description for attachment.              -->
          <!-- ispatch      : Whether attachment is a patch file.            -->
          <!-- filename     : Filename of attachment.                        -->
          <!-- submitter_id : Issuezilla ID of attachement submitter.        --> 
          <!-- submitting_username    : username of attachement submitter.   --> 
          <!-- data         : Encoded attachment.                            --> 
          <!-- attachment_iz_url : URL to attachment in iz.                  --> 
    
          <!ELEMENT mimetype (#PCDATA)>
          <!ELEMENT attachid (#PCDATA)>
          <!ELEMENT date (#PCDATA)>   
          <!ELEMENT desc (#PCDATA)>  
          <!ELEMENT ispatch (#PCDATA)>
          <!ELEMENT filename (#PCDATA)> 
          <!ELEMENT submitter_id (#PCDATA)> 
          <!ELEMENT submitting_username (#PCDATA)> 
          <!ELEMENT data (#PCDATA)>    
          <!ELEMENT attachment_iz_url (#PCDATA)>    
    
        <!-- Data pertaining to the issue's activity record.                 -->
        
        <!ELEMENT activity (user, when, field_name, field_desc, oldvalue, 
            newvalue)>
    
          <!-- user         : user who performed the action                  -->
          <!-- when         : date the described change was made             -->
          <!-- field_name   : name of db field (in fielddefs)                -->
          <!-- field_desc   : description of the database field              -->
          <!-- oldvalue     : value changed from                             -->
          <!-- newvalue     : value changed to                               -->
    
          <!ELEMENT user (#PCDATA)>
          <!ELEMENT when (#PCDATA)>
          <!ELEMENT field_name (#PCDATA)>
          <!ELEMENT field_desc (#PCDATA)>
          <!ELEMENT oldvalue (#PCDATA)>
          <!ELEMENT newvalue (#PCDATA)>
    
    
]>
<issuezilla exporter="guest" charset="UTF-8" version="2.11" urlbase="https://ofbiz.dev.java.net/issues/" maintainer="owner@ofbiz.dev.java.net" project_domain="dev.java.net" project_name="ofbiz" project_id="792" dtd_version="Revision: 1.2">
<issue status_code="200" status_message="OK">
  <issue_id>1</issue_id>
  <issue_status>RESOLVED</issue_status>
  <priority>P3</priority>
  <resolution>FIXED</resolution>
  <component>Documentation</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20030820210924</delta_ts>
  <subcomponent>website</subcomponent>
  <reporter>ajzeneski</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-08-13 22:35:10</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>Website missing</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-13 22:35:10</issue_when>
   <thetext>Website is missing from CVS.</thetext>
  </long_desc>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-19 12:09:17</issue_when>
   <thetext>Website starting to move</thetext>
  </long_desc>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-19 12:11:57</issue_when>
   <thetext>Changed milestone</thetext>
  </long_desc>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-20 21:09:24</issue_when>
   <thetext>Website has been imported into CVS</thetext>
  </long_desc>
  <activity>
    <user>ajzeneski</user>
    <when>2003-08-19 12:09:17</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>NEW</oldvalue>
    <newvalue>STARTED</newvalue>
  </activity>
  <activity>
    <user>ajzeneski</user>
    <when>2003-08-19 12:09:17</when>
    <field_name>version</field_name>
    <field_desc>Version</field_desc>
    <oldvalue>unspecified</oldvalue>
    <newvalue>CVS</newvalue>
  </activity>
  <activity>
    <user>ajzeneski</user>
    <when>2003-08-19 12:11:57</when>
    <field_name>target_milestone</field_name>
    <field_desc>Target Milestone</field_desc>
    <oldvalue>milestone 1</oldvalue>
    <newvalue>not determined</newvalue>
  </activity>
  <activity>
    <user>ajzeneski</user>
    <when>2003-08-20 21:09:24</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>STARTED</oldvalue>
    <newvalue>RESOLVED</newvalue>
  </activity>
  <activity>
    <user>ajzeneski</user>
    <when>2003-08-20 21:09:24</when>
    <field_name>resolution</field_name>
    <field_desc>Resolution</field_desc>
    <oldvalue></oldvalue>
    <newvalue>FIXED</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>2</issue_id>
  <issue_status>RESOLVED</issue_status>
  <priority>P3</priority>
  <resolution>FIXED</resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>jonesde</assigned_to>
  <delta_ts>20030824004146</delta_ts>
  <subcomponent>Product</subcomponent>
  <reporter>ajzeneski</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-08-23 14:25:20</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>Missing FTL</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-23 14:25:20</issue_when>
   <thetext>Missing FTL file:

Error: File not found: /feature/EditFeatureCategoryFeatures.ftl</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-08-24 00:41:46</issue_when>
   <thetext>Converted JSP to FTL, made some small corrections.</thetext>
  </long_desc>
  <activity>
    <user>jonesde</user>
    <when>2003-08-24 00:41:46</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>NEW</oldvalue>
    <newvalue>RESOLVED</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-08-24 00:41:46</when>
    <field_name>resolution</field_name>
    <field_desc>Resolution</field_desc>
    <oldvalue></oldvalue>
    <newvalue>FIXED</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>3</issue_id>
  <issue_status>RESOLVED</issue_status>
  <priority>P3</priority>
  <resolution>FIXED</resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20030828103031</delta_ts>
  <subcomponent>Product</subcomponent>
  <reporter>ajzeneski</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-08-23 14:27:14</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>Edit Promo Bug</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-23 14:27:14</issue_when>
   <thetext>When editing a promo rule; the drop down for the current condition contains only
the existing condition (many times).</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-08-28 10:30:31</issue_when>
   <thetext>#list directive had a type. Fix in CVS.</thetext>
  </long_desc>
  <activity>
    <user>jonesde</user>
    <when>2003-08-28 10:30:31</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>NEW</oldvalue>
    <newvalue>RESOLVED</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-08-28 10:30:31</when>
    <field_name>resolution</field_name>
    <field_desc>Resolution</field_desc>
    <oldvalue></oldvalue>
    <newvalue>FIXED</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>4</issue_id>
  <issue_status>VERIFIED</issue_status>
  <priority>P3</priority>
  <resolution>FIXED</resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20030828103057</delta_ts>
  <subcomponent>Product</subcomponent>
  <reporter>ajzeneski</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-08-23 14:30:52</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>Price Rule Bug</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-23 14:30:52</issue_when>
   <thetext>When editing a price rule; changing the is &quot;sale price&quot; flag sets properly,
however always displays &quot;no&quot; as the selected choice.</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-08-28 10:20:59</issue_when>
   <thetext>Fixed conditional on the no button, now appears correctly.</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-08-28 10:30:57</issue_when>
   <thetext>Done</thetext>
  </long_desc>
  <activity>
    <user>jonesde</user>
    <when>2003-08-28 10:20:59</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>NEW</oldvalue>
    <newvalue>RESOLVED</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-08-28 10:20:59</when>
    <field_name>resolution</field_name>
    <field_desc>Resolution</field_desc>
    <oldvalue></oldvalue>
    <newvalue>FIXED</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-08-28 10:30:57</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>RESOLVED</oldvalue>
    <newvalue>VERIFIED</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>5</issue_id>
  <issue_status>NEW</issue_status>
  <priority>P3</priority>
  <resolution></resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20030823144138</delta_ts>
  <subcomponent>Party</subcomponent>
  <reporter>ajzeneski</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-08-23 14:41:38</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>Relationship missing button</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-08-23 14:41:38</issue_when>
   <thetext>View/Edit party relationships page first is still JSP and second is missing the
links to communication event(s).</thetext>
  </long_desc>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>6</issue_id>
  <issue_status>CLOSED</issue_status>
  <priority>P3</priority>
  <resolution>INVALID</resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20030918144334</delta_ts>
  <subcomponent>Entity</subcomponent>
  <reporter>robdawson</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-09-04 02:09:57</creation_ts>
  <qa_contact>jonesde</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>Entity Engine ConnectionFactory and DBCPConnectionFactory issues with Oracle</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>robdawson</who>
   <issue_when>2003-09-04 02:09:57</issue_when>
   <thetext>When using the Inline JDBC Functionality of the Entity Engine to access an Oracle 
database the Entity Engine gives SQL no suitable driver exceptions.

The fix for this involves changing:
                loader.loadClass(driverClassName);
to
                Class clazz = loader.loadClass(driverClassName);
                clazz.newInstance();
in both the ConnectionFactory and DBCPConnectionFactory classes.

There will also need to be the appropriate exception handling.

Please contact me if this requires any clarification.</thetext>
  </long_desc>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-09-04 22:15:06</issue_when>
   <thetext>The message you are getting means that the JDBC drivers for Oracle cannot be
found on the classpath. Contact the users mailing list if you need further help
with this issue.</thetext>
  </long_desc>
  <long_desc>
   <who>ajzeneski</who>
   <issue_when>2003-09-04 22:17:28</issue_when>
   <thetext>Sorry; DBCP support is currently outdated and not used due to the fact that
there is no transaction support. It is recommended you use the JOTM/XAPool
connections. This issue will be addressed during a refactor of this class in the
coming months.</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-09-18 14:43:34</issue_when>
   <thetext>
This issue has been resolved with code changes similar to those recommended.

HOWEVER: There is one caveat with this: I would NOT recommend running using
either of these blocks of code. Without a transaction aware connection pool
performance will be severely affected or operations may be performed outside of
transactions. So, I wouldn&apos;t use straight JDBC or DBCP right now. Hopefully in
the future DBCP will support XADataSources, then it may be an option.

Later,
-David Jones
</thetext>
  </long_desc>
  <activity>
    <user>ajzeneski</user>
    <when>2003-09-04 22:15:06</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>NEW</oldvalue>
    <newvalue>RESOLVED</newvalue>
  </activity>
  <activity>
    <user>ajzeneski</user>
    <when>2003-09-04 22:15:06</when>
    <field_name>resolution</field_name>
    <field_desc>Resolution</field_desc>
    <oldvalue></oldvalue>
    <newvalue>INVALID</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-09-18 14:43:34</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>RESOLVED</oldvalue>
    <newvalue>CLOSED</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-09-18 14:43:34</when>
    <field_name>qa_contact</field_name>
    <field_desc>QA Contact</field_desc>
    <oldvalue>issues@ofbiz</oldvalue>
    <newvalue>jonesde</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>7</issue_id>
  <issue_status>NEW</issue_status>
  <priority>P4</priority>
  <resolution></resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20040304194045</delta_ts>
  <subcomponent>WebTools</subcomponent>
  <reporter>fzhu_genshare</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-09-21 07:35:08</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc>http://localhost:8080/webtools/control/view/ModelGroupWriter?savetofile=true</issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>&quot;Save Entity Group XML to File&quot; error</short_desc>
  <keywords></keywords>
  <has_duplicates>
    <issue_id>8</issue_id>
    <who>jonesde</who>
    <when>2003-11-04 01:04:02</when>
  </has_duplicates>
  <long_desc>
   <who>fzhu_genshare</who>
   <issue_when>2003-09-21 07:35:08</issue_when>
   <thetext>If click &quot;Save Entity Group XML to File&quot; on the webtools, the new page opens and 
the following error message appears: 

org.apache.jasper.JasperException: Unable to compile class for JSP

An error occurred at line: -1 in the jsp file: null

Generated servlet error:
[javac] Since fork is true, ignoring compiler setting.
[javac] Compiling 1 source file
[javac] Since fork is true, ignoring compiler setting.
[javac] C:\DOCUME~1\ADMINI~1\LOCALS~1
\Temp\Jetty_0_0_0_0_8080__webtools\entity\ModelGroupWriter_jsp.java:72: 
cannot resolve symbol
[javac] symbol : variable entityGroupResourceHandler 
[javac] location: class org.ofbiz.entity.model.ModelGroupReader
[javac] ResourceHandler resourceHandler = 
modelGroupReader.entityGroupResourceHandler;
[javac] ^
[javac] 1 error</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-11-04 01:04:02</issue_when>
   <thetext>*** Issue 8 has been marked as a duplicate of this issue. ***</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2004-03-04 19:40:45</issue_when>
   <thetext>lower priority</thetext>
  </long_desc>
  <activity>
    <user>jonesde</user>
    <when>2004-03-04 19:40:45</when>
    <field_name>priority</field_name>
    <field_desc>Priority</field_desc>
    <oldvalue>P3</oldvalue>
    <newvalue>P4</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>8</issue_id>
  <issue_status>RESOLVED</issue_status>
  <priority>P3</priority>
  <resolution>DUPLICATE</resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20031104010402</delta_ts>
  <subcomponent>WebTools</subcomponent>
  <reporter>fzhu_genshare</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-09-21 07:40:53</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc>http://localhost:8080/webtools/control/view/ModelGroupWriter</issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>&quot;Generate Entity Group XML&quot; error</short_desc>
  <keywords></keywords>
  <is_duplicate>
    <issue_id>7</issue_id>
    <who>jonesde</who>
    <when>2003-11-04 01:04:02</when>
  </is_duplicate>
  <long_desc>
   <who>fzhu_genshare</who>
   <issue_when>2003-09-21 07:40:53</issue_when>
   <thetext>If clicked &quot;Generate Entity Group XML&quot; on webtools, an error message occurs:

org.apache.jasper.JasperException: Unable to compile class for JSP

An error occurred at line: -1 in the jsp file: null

Generated servlet error:
[javac] Since fork is true, ignoring compiler setting.
[javac] Compiling 1 source file
[javac] Since fork is true, ignoring compiler setting.
[javac] C:\DOCUME~1\ADMINI~1\LOCALS~1
\Temp\Jetty_0_0_0_0_8080__webtools\entity\ModelGroupWriter_jsp.java:72: 
cannot resolve symbol
[javac] symbol : variable entityGroupResourceHandler 
[javac] location: class org.ofbiz.entity.model.ModelGroupReader
[javac] ResourceHandler resourceHandler = 
modelGroupReader.entityGroupResourceHandler;
[javac] ^
[javac] 1 error

It seems the class ResourceHandler is missing. The same error result in several 
links of webtools concerning entity engine xml export broken.</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2003-11-04 01:04:02</issue_when>
   <thetext>This issue is a duplicate of #7, they may be different links but they hit the same 
request and code.

*** This issue has been marked as a duplicate of 7 ***</thetext>
  </long_desc>
  <activity>
    <user>jonesde</user>
    <when>2003-11-04 01:04:02</when>
    <field_name>issue_status</field_name>
    <field_desc>Status</field_desc>
    <oldvalue>NEW</oldvalue>
    <newvalue>RESOLVED</newvalue>
  </activity>
  <activity>
    <user>jonesde</user>
    <when>2003-11-04 01:04:02</when>
    <field_name>resolution</field_name>
    <field_desc>Resolution</field_desc>
    <oldvalue></oldvalue>
    <newvalue>DUPLICATE</newvalue>
  </activity>
</issue>
<issue status_code="200" status_message="OK">
  <issue_id>9</issue_id>
  <issue_status>RESOLVED</issue_status>
  <priority>P3</priority>
  <resolution>WONTFIX</resolution>
  <component>Components</component>
  <version>CVS</version>
  <rep_platform>All</rep_platform>
  <assigned_to>issues@ofbiz</assigned_to>
  <delta_ts>20040223211140</delta_ts>
  <subcomponent>Entity</subcomponent>
  <reporter>byersa</reporter>
  <target_milestone>not determined</target_milestone>
  <issue_type>DEFECT</issue_type>
  <creation_ts>2003-10-28 09:27:31</creation_ts>
  <qa_contact>issues@ofbiz</qa_contact>
  <status_whiteboard></status_whiteboard>
  <issue_file_loc></issue_file_loc>
  <votes></votes>
  <op_sys>All</op_sys>
  <short_desc>GenericEntity.getBytes fails with HSQLDB</short_desc>
  <keywords></keywords>
  <long_desc>
   <who>byersa</who>
   <issue_when>2003-10-28 09:27:31</issue_when>
   <thetext>getBytes internally casts to ByteWrapper which causes a ClassCastException.
Casting directly to byte[] seems to work.

Don&apos;t know if it fails with other dbs.</thetext>
  </long_desc>
  <long_desc>
   <who>jonesde</who>
   <issue_when>2004-02-23 21:11:40</issue_when>
   <thetext>This does not appear to be something that can be fixed in OFBiz, it appears to be a bug in HSQLDB, and 