<?xml version="1.0" encoding="ISO-8859-1"?><?pos="3"?>
<!-- generated by hnb 1.9.17 (http://hnb.sourceforge.net) -->

<!DOCTYPE tree[
	<!ELEMENT tree (node*)>
	<!ELEMENT data (#PCDATA)> <!-- (max 4096 bytes long) -->
	<!ELEMENT node (data?,node*)>
	<!ATTLIST node done (yes|no) #IMPLIED
	          type CDATA #IMPLIED
	>]>

<tree>
<node done="no" type="todo"><data>Next_Actions</data>
	<node done="no" type="todo"><data>@class</data></node>
	<node done="no" type="todo"><data>@agenda</data>
		<node done="yes" type="todo"><data>this is something I&apos;d like to do</data></node>
	</node>
	<node done="no" type="todo"><data>@dorm</data>
		<node done="no" type="todo"><data>clean room</data></node>
	</node>
	<node done="no" type="todo"><data>@computer</data>
		<node done="no" type="todo"><data>Write general makefile for cs projects</data></node>
		<node done="no" type="todo"><data>Set up bash podder</data></node>
	</node>
	<node done="no" type="todo"><data>@errands</data>
		<node done="no" type="todo"><data>Purchase geo lab book</data></node>
	</node>
	<node done="no" type="todo"><data>@dublin</data></node>
</node>
<node><data>projects</data></node>
</tree>
